/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.Controller;
import Controllers.DatosAFN;
import Models.AFN;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moon1
 */
public class AFD extends javax.swing.JFrame {
    
    /**
     * Creates new form AFD
     */
    public AFD() {
        initComponents();
        setLocationRelativeTo(null);
        this.repaint();
        
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Posición", "AFN", "Token", "Seleccionar"}, 0);
        AFD_Table.setModel(modelo);
        
    }
    
    public void setController(Controller c){
        OKAFD_btn.addActionListener(c);
        OutAFD_btn.addActionListener(c);
    }
    
    public void llenarTablaAFN(DatosAFN datos) {
        modelo = (DefaultTableModel) AFD_Table.getModel(); // usa la variable de instancia
    modelo.setRowCount(0); // limpiar tabla

    int pos = 1;
    for (AFN afn : datos.getListaAFN()) {
        modelo.addRow(new Object[]{
            pos,
            afn.toString(),
            "",
            Boolean.FALSE
        });
        pos++;
    }
    }

    
    DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Posición", "AFN", "Token", "Seleccionar"}, 0) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch (columnIndex) {
                case 0:
                case 1:
                    return String.class;
                case 2:
                    return String.class; // Token editable
                case 3:
                    return Boolean.class; // Checkbox
                default:
                    return Object.class;
            }
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            // Solo el Token y el checkbox son editables
            return column == 2 || column == 3;
        }
    };
    
    public AbstractMap.SimpleEntry<List<AFN>, List<String>> obtenerSeleccion(DatosAFN datosAFN) {
        List<AFN> seleccionados = new ArrayList<>();
        List<String> tokens = new ArrayList<>();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object valor = modelo.getValueAt(i, 3);
            System.out.println("Fila " + i + " valor columna 3 = " + valor + " (" + 
                           (valor != null ? valor.getClass().getSimpleName() : "null") + ")");
        
            boolean seleccionado = false;
           
            if (valor instanceof Boolean) {
                seleccionado = (Boolean) valor;
            } else if (valor instanceof String) {
                seleccionado = ((String) valor).equalsIgnoreCase("true");
            }

            if (seleccionado) {
                String token = (String) modelo.getValueAt(i, 2);
                if (token == null || token.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, 
                        "Debe ingresar un token para el AFN seleccionado en la fila " + i);
                    return null;
                }
                seleccionados.add(datosAFN.getListaAFN().get(i));
                tokens.add(token.trim());
            }
        }

        return new AbstractMap.SimpleEntry<>(seleccionados, tokens);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKAFD_btn = new javax.swing.JButton();
        OutAFD_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AFD_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Convertir AFN a AFD");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKAFD_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKAFD_btn.setText("Aceptar");
        OKAFD_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKAFD_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKAFD_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKAFD_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        OutAFD_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutAFD_btn.setText("Cancelar");
        OutAFD_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OutAFD_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutAFD_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutAFD_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seleccione los ANF para la creación del AFD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        AFD_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Posición", "AFN", "Token", "Selección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AFD_Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 560, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKAFD_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKAFD_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKAFD_btnActionPerformed

    private void OutAFD_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutAFD_btnActionPerformed
        /*/ Accion para que el boton de salir funcione
        if(evt.getSource()== OutU_btn){
            dispose(); // Cierra la ventana actual

            Views.MainPage inicio = new Views.MainPage(); // Crea la nueva ventana
            Controlers.Controller controller = new Controlers.Controller(inicio); // Asocia el controlador
            inicio.setVisible(true); // Muestra el MainPage
        }*/
    }//GEN-LAST:event_OutAFD_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AFD_Table;
    public javax.swing.JButton OKAFD_btn;
    public javax.swing.JButton OutAFD_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
