/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Calculadora;
import Controllers.Controller;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author moon1
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    private File AFDt;
    public String afd;
    
    public Calc() {
        initComponents();
        setLocationRelativeTo(null);
        this.afd ="";
        this.repaint();
    }
    
    public void setController(Controller c){
        OKCalc_btn.addActionListener(c);
        OutCalc_btn.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKCalc_btn = new javax.swing.JButton();
        OutCalc_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Selec_btn = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ExA_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NotPos_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Eval_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calculadora");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKCalc_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKCalc_btn.setText("Aceptar");
        OKCalc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKCalc_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKCalc_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        OutCalc_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutCalc_btn.setText("Cancelar");
        OutCalc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutCalc_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutCalc_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Notación postfijo de la expresión");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        Selec_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carpeta.png"))); // NOI18N
        Selec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selec_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Selec_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 280, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Seleccione el AFD");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel1.add(ExA_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 320, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Expresión aritmética a evaluar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel1.add(NotPos_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Notación postfijo de la expresión");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(Eval_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 320, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKCalc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKCalc_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKCalc_btnActionPerformed

    private void OutCalc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutCalc_btnActionPerformed

    }//GEN-LAST:event_OutCalc_btnActionPerformed

    private void Selec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selec_btnActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        // Opcional: establecer el directorio inicial
        fileChooser.setCurrentDirectory(new java.io.File(System.getProperty("user.home")));

        // Mostrar el cuadro de diálogo para abrir archivos
        int resultado = fileChooser.showOpenDialog(this);

        // Si el usuario seleccionó un archivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = fileChooser.getSelectedFile();

            // Mostrar la ruta completa en el JTextField
            txtRuta.setText(archivoSeleccionado.getAbsolutePath());

            // Si quieres solo el nombre del archivo:
            // txtRuta.setText(archivoSeleccionado.getName());
            
            AFDt = archivoSeleccionado;
            try{
                afd = new String(java.nio.file.Files.readAllBytes(AFDt.toPath())) ;
                //JOptionPane.showMessageDialoge(null, "AFD cargado correctamente.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(rootPane, "AFD cargado correctamente.");
            }catch (Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Error al cargar AFD");
            }
        }
    }//GEN-LAST:event_Selec_btnActionPerformed

    public void setResult(String r){
        Eval_txt.setText(r);
    }
    public void setPostF(String r){
        NotPos_txt.setText(r);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Eval_txt;
    public javax.swing.JTextField ExA_txt;
    public javax.swing.JTextField NotPos_txt;
    public javax.swing.JButton OKCalc_btn;
    public javax.swing.JButton OutCalc_btn;
    public javax.swing.JButton Selec_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
