/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.Controller;
import Controllers.DatosAFN;
import Models.AFN;
import java.util.List;

/**
 *
 * @author moon1
 */
public class CerrO extends javax.swing.JFrame {
    private DatosAFN datos;
    /**
     * Creates new form CerrO
     */
    public CerrO(DatosAFN datos) {
        initComponents();
        setLocationRelativeTo(null);
        this.datos = datos;
        this.repaint();
    }
    
    public void cargarAFN(List<AFN> lista) {
        Ep_box.removeAllItems();
                        
        if (datos == null) {
            System.out.println("⚠️ datos es null");
            return;
        }

        for (int i = 1; datos.getListaAFN().size() >= i; i++) {
            Ep_box.addItem("AFN " + i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKO_btn = new javax.swing.JButton();
        OutO_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Ep_box = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cerradura ?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKO_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKO_btn.setText("Aceptar");
        OKO_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKO_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKO_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        OutO_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutO_btn.setText("Cancelar");
        OutO_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutO_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutO_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Aplicar a:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        Ep_box.setBackground(new java.awt.Color(255, 255, 255));
        Ep_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Ep_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CerrO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKO_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKO_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKO_btnActionPerformed

    private void OutO_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutO_btnActionPerformed
        
    }//GEN-LAST:event_OutO_btnActionPerformed

    public void setController(Controller c){
        OKO_btn.addActionListener(c);
        OutO_btn.addActionListener(c);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CerrO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CerrO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CerrO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CerrO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatosAFN datos = new DatosAFN();
                new CerrO(datos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Ep_box;
    public javax.swing.JButton OKO_btn;
    public javax.swing.JButton OutO_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
