/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.*;
//import Models.*;

/**
 *
 * @author moon1
 */
public class CrearBasico2 extends javax.swing.JFrame {
    /**
     * Creates new form CrearBasico2
     */
    public CrearBasico2() {
        initComponents();
        setLocationRelativeTo(null);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKCB2_btn = new javax.swing.JButton();
        OutCB2_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_charS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_charI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear Básico 2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKCB2_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKCB2_btn.setText("Aceptar");
        OKCB2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKCB2_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKCB2_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        OutCB2_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutCB2_btn.setText("Cancelar");
        OutCB2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutCB2_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutCB2_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CB2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, 70));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Caracter S:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txt_charS.setBackground(new java.awt.Color(255, 255, 255));
        txt_charS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_charSActionPerformed(evt);
            }
        });
        jPanel1.add(txt_charS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 110, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Caracter I:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        txt_charI.setBackground(new java.awt.Color(255, 255, 255));
        txt_charI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_charIActionPerformed(evt);
            }
        });
        jPanel1.add(txt_charI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OutCB2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutCB2_btnActionPerformed
        
    }//GEN-LAST:event_OutCB2_btnActionPerformed

    private void txt_charSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_charSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_charSActionPerformed

    private void txt_charIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_charIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_charIActionPerformed

    private void OKCB2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKCB2_btnActionPerformed
        
    }//GEN-LAST:event_OKCB2_btnActionPerformed

    public void setController(Controller c){
        OKCB2_btn.addActionListener(c);
        OutCB2_btn.addActionListener(c);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearBasico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearBasico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearBasico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearBasico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearBasico2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton OKCB2_btn;
    public javax.swing.JButton OutCB2_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txt_charI;
    public javax.swing.JTextField txt_charS;
    // End of variables declaration//GEN-END:variables
}
