/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.Controller;
import javax.swing.JFileChooser;

/**
 *
 * @author moon1
 */
public class ERtoAFN extends javax.swing.JFrame {

    /**
     * Creates new form ERtoAFN
     */
    public ERtoAFN() {
        initComponents();
        setLocationRelativeTo(null);
        this.repaint();
    }
    
    public void setController(Controller c){
        OKER_btn.addActionListener(c);
        OutER_btn.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKER_btn = new javax.swing.JButton();
        OutER_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Selec_btn = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ER_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Expresión Regular to AFN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKER_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKER_btn.setText("Aceptar");
        OKER_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKER_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKER_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        OutER_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutER_btn.setText("Cancelar");
        OutER_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutER_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutER_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seleccione el AFD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Selec_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carpeta.png"))); // NOI18N
        Selec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selec_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Selec_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 330, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Introduzca la expresión regular:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        ER_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ER_txtActionPerformed(evt);
            }
        });
        jPanel1.add(ER_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 370, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKER_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKER_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKER_btnActionPerformed

    private void OutER_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutER_btnActionPerformed

    }//GEN-LAST:event_OutER_btnActionPerformed

    private void Selec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selec_btnActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        // Opcional: establecer el directorio inicial
        fileChooser.setCurrentDirectory(new java.io.File(System.getProperty("user.home")));

        // Mostrar el cuadro de diálogo para abrir archivos
        int resultado = fileChooser.showOpenDialog(this);

        // Si el usuario seleccionó un archivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = fileChooser.getSelectedFile();

            // Mostrar la ruta completa en el JTextField
            txtRuta.setText(archivoSeleccionado.getAbsolutePath());

            // Si quieres solo el nombre del archivo:
            // txtRuta.setText(archivoSeleccionado.getName());
        }
    }//GEN-LAST:event_Selec_btnActionPerformed

    private void ER_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ER_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ER_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERtoAFN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERtoAFN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERtoAFN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERtoAFN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERtoAFN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ER_txt;
    public javax.swing.JButton OKER_btn;
    public javax.swing.JButton OutER_btn;
    public javax.swing.JButton Selec_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
