/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.Controller;
import javax.swing.JFileChooser;

/**
 *
 * @author moon1
 */
public class GdG extends javax.swing.JFrame {

    /**
     * Creates new form GdG
     */
    public GdG() {
        initComponents();
        setLocationRelativeTo(null);
        this.repaint();
        
    }
    
    public void setController(Controller c){
        OKGG_btn.addActionListener(c);
        OutGG_btn.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKGG_btn = new javax.swing.JButton();
        OutGG_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        Selec_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AL_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Simb_Table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FIRST_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        SimbNT_table = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        FOLLOW_table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descenso recursivo Gramática de Gramáticas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKGG_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKGG_btn.setText("Aceptar");
        OKGG_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKGG_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKGG_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKGG_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        OutGG_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutGG_btn.setText("Cancelar");
        OutGG_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OutGG_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutGG_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutGG_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cadena a analizar sintácticamente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 280, -1));

        Selec_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carpeta.png"))); // NOI18N
        Selec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selec_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Selec_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Símbolos term y no term");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        AL_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AL_txtActionPerformed(evt);
            }
        });
        jPanel1.add(AL_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 370, -1));

        Simb_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Símbolo", "Terminal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Simb_Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 290));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Seleccione el AFD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        FIRST_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Símbolo"
            }
        ));
        jScrollPane2.setViewportView(FIRST_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, 180));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Símbolos no terminales");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 70, -1, -1));

        SimbNT_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Símbolo"
            }
        ));
        jScrollPane3.setViewportView(SimbNT_table);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 140, 300));

        FOLLOW_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Símbolo"
            }
        ));
        jScrollPane4.setViewportView(FOLLOW_table);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 130, 180));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tabla FIRST");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tabla FOLLOW");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKGG_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKGG_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKGG_btnActionPerformed

    private void OutGG_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutGG_btnActionPerformed
        
    }//GEN-LAST:event_OutGG_btnActionPerformed

    private void Selec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selec_btnActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        // Opcional: establecer el directorio inicial
        fileChooser.setCurrentDirectory(new java.io.File(System.getProperty("user.home")));

        // Mostrar el cuadro de diálogo para abrir archivos
        int resultado = fileChooser.showOpenDialog(this);

        // Si el usuario seleccionó un archivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = fileChooser.getSelectedFile();

            // Mostrar la ruta completa en el JTextField
            txtRuta.setText(archivoSeleccionado.getAbsolutePath());

            // Si quieres solo el nombre del archivo:
            // txtRuta.setText(archivoSeleccionado.getName());
        }
    }//GEN-LAST:event_Selec_btnActionPerformed

    private void AL_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AL_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AL_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GdG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GdG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GdG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GdG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GdG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AL_txt;
    private javax.swing.JTable FIRST_table;
    private javax.swing.JTable FOLLOW_table;
    public javax.swing.JButton OKGG_btn;
    public javax.swing.JButton OutGG_btn;
    public javax.swing.JButton Selec_btn;
    private javax.swing.JTable SimbNT_table;
    private javax.swing.JTable Simb_Table;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
