/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.Controller;

/**
 *
 * @author moon1
 */
public class LL1 extends javax.swing.JFrame {

    /**
     * Creates new form LL1
     */
    public LL1() {
        initComponents();
        setLocationRelativeTo(null);
        this.repaint();
        
    }
    
    public void setController (Controller c){
        OKLL1_btn.addActionListener(c);
        OutLL1_btn.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKLL1_btn = new javax.swing.JButton();
        OutLL1_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        Selec_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FIRST_table = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        FOLLOW_table = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 32, 36));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Análisis LL(1)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jPanel1.setBackground(new java.awt.Color(232, 221, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OKLL1_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OKLL1_btn.setText("Aceptar");
        OKLL1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKLL1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKLL1_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OKLL1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        OutLL1_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        OutLL1_btn.setText("Cancelar");
        OutLL1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OutLL1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutLL1_btnActionPerformed(evt);
            }
        });
        jPanel1.add(OutLL1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Gramática:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 280, -1));

        Selec_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carpeta.png"))); // NOI18N
        Selec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selec_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Selec_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Seleccione el AFD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        FIRST_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "No terminal"
            }
        ));
        jScrollPane2.setViewportView(FIRST_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, 110));

        FOLLOW_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Terminal", "Token"
            }
        ));
        jScrollPane4.setViewportView(FOLLOW_table);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 170, 110));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 370, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKLL1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKLL1_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKLL1_btnActionPerformed

    private void OutLL1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutLL1_btnActionPerformed

    }//GEN-LAST:event_OutLL1_btnActionPerformed

    private void Selec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selec_btnActionPerformed
        /*JFileChooser fileChooser = new JFileChooser();

        // Opcional: establecer el directorio inicial
        fileChooser.setCurrentDirectory(new java.io.File(System.getProperty("user.home")));

        // Mostrar el cuadro de diálogo para abrir archivos
        int resultado = fileChooser.showOpenDialog(this);

        // Si el usuario seleccionó un archivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = fileChooser.getSelectedFile();

            // Mostrar la ruta completa en el JTextField
            txtRuta.setText(archivoSeleccionado.getAbsolutePath());

            // Si quieres solo el nombre del archivo:
            // txtRuta.setText(archivoSeleccionado.getName());
        }*/
    }//GEN-LAST:event_Selec_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LL1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LL1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LL1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LL1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LL1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FIRST_table;
    private javax.swing.JTable FOLLOW_table;
    public javax.swing.JButton OKLL1_btn;
    public javax.swing.JButton OutLL1_btn;
    public javax.swing.JButton Selec_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
