/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.DatosAFN;
/**
 *
 * @author moon1
 */
public class Principal extends javax.swing.JFrame {
    private DatosAFN datos;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        this.repaint();
    }
    
    public Principal(DatosAFN datos) {
        this.datos = datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CB2_btn = new javax.swing.JButton();
        U_btn = new javax.swing.JButton();
        Con_btn = new javax.swing.JButton();
        CK_btn = new javax.swing.JButton();
        AL_btn = new javax.swing.JButton();
        CP_btn = new javax.swing.JButton();
        CO_btn = new javax.swing.JButton();
        AFD_btn = new javax.swing.JButton();
        MAFN_btn = new javax.swing.JButton();
        ER_btn = new javax.swing.JButton();
        CB_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Ca_btn = new javax.swing.JButton();
        LL1_btn = new javax.swing.JButton();
        GdG_btn = new javax.swing.JButton();
        LR0_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(99, 32, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSTITUTO POLITECNICO NACIONAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ipn-2 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, -1, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo_ESCOM (2).png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 75));

        jPanel2.setBackground(new java.awt.Color(14, 20, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MENU");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        CB2_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CB2_btn.setText("Crear Basico 2");
        CB2_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(CB2_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        U_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        U_btn.setText("Unir");
        U_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(U_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, -1));

        Con_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Con_btn.setText("Concatenar");
        Con_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Con_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, -1));

        CK_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CK_btn.setText("Cerradura *");
        CK_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CK_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CK_btnActionPerformed(evt);
            }
        });
        jPanel2.add(CK_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, -1));

        AL_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        AL_btn.setText("Analiz-Lexic");
        AL_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AL_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AL_btnActionPerformed(evt);
            }
        });
        jPanel2.add(AL_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, -1));

        CP_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CP_btn.setText("Cerradura +");
        CP_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(CP_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, -1));

        CO_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CO_btn.setText("Cerradura ?");
        CO_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CO_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CO_btnActionPerformed(evt);
            }
        });
        jPanel2.add(CO_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, -1));

        AFD_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        AFD_btn.setText("AFN -> AFD");
        AFD_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AFD_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFD_btnActionPerformed(evt);
            }
        });
        jPanel2.add(AFD_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, -1));

        MAFN_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        MAFN_btn.setText("Mostrar AFN");
        MAFN_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MAFN_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAFN_btnActionPerformed(evt);
            }
        });
        jPanel2.add(MAFN_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, -1));

        ER_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ER_btn.setText("ER -> AFN");
        ER_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ER_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ER_btnActionPerformed(evt);
            }
        });
        jPanel2.add(ER_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, -1));

        CB_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CB_btn.setText("Crear Basico");
        CB_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(CB_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 130, 430));

        jPanel3.setBackground(new java.awt.Color(232, 221, 221));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("COMPILADORES");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AFD_im.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 320, 160));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Proyecto 1:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Automatas Finitos Deterministas y No Deterministas ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));
        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 75, 670, 430));

        jPanel4.setBackground(new java.awt.Color(14, 20, 28));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sintáctico");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 30));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Analizador");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        Ca_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Ca_btn.setText("Calculadora");
        Ca_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ca_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ca_btnActionPerformed(evt);
            }
        });
        jPanel4.add(Ca_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        LL1_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        LL1_btn.setText("LL(1)");
        LL1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LL1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LL1_btnActionPerformed(evt);
            }
        });
        jPanel4.add(LL1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, -1));

        GdG_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        GdG_btn.setText("Gram d Gram");
        GdG_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GdG_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GdG_btnActionPerformed(evt);
            }
        });
        jPanel4.add(GdG_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));

        LR0_btn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        LR0_btn.setText("LR (0)");
        LR0_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LR0_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LR0_btnActionPerformed(evt);
            }
        });
        jPanel4.add(LR0_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 75, 130, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CK_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CK_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CK_btnActionPerformed

    private void AL_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AL_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AL_btnActionPerformed

    private void CO_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CO_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CO_btnActionPerformed

    private void AFD_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFD_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFD_btnActionPerformed

    private void MAFN_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAFN_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MAFN_btnActionPerformed

    private void ER_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ER_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ER_btnActionPerformed

    private void GdG_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GdG_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GdG_btnActionPerformed

    private void Ca_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ca_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ca_btnActionPerformed

    private void LL1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LL1_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LL1_btnActionPerformed

    private void LR0_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LR0_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LR0_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*Views.Principal mainPage = new Views.Principal();   // crear la ventana
                Controllers.Controller controller = new Controllers.Controller(mainPage); // conectar controlador
                mainPage.setVisible(true); // mostrar ventana
                new Principal().setVisible(true);*/
                new Controllers.Controller();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AFD_btn;
    public javax.swing.JButton AL_btn;
    public javax.swing.JButton CB2_btn;
    public javax.swing.JButton CB_btn;
    public javax.swing.JButton CK_btn;
    public javax.swing.JButton CO_btn;
    public javax.swing.JButton CP_btn;
    public javax.swing.JButton Ca_btn;
    public javax.swing.JButton Con_btn;
    public javax.swing.JButton ER_btn;
    public javax.swing.JButton GdG_btn;
    public javax.swing.JButton LL1_btn;
    public javax.swing.JButton LR0_btn;
    public javax.swing.JButton MAFN_btn;
    public javax.swing.JButton U_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
