package org.netbeans.lib.awtextra;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.LayoutManager;

/** Minimal stub of NetBeans AbsoluteLayout to allow compilation.
 * This is not a full implementation; it provides basic no-op behavior
 * sufficient for compiling and running simple UIs generated by NetBeans.
 */
public class AbsoluteLayout implements LayoutManager {

    public AbsoluteLayout() { }

    @Override
    public void addLayoutComponent(String name, Component comp) { }

    @Override
    public void removeLayoutComponent(Component comp) { }

    @Override
    public Dimension preferredLayoutSize(Container parent) { return parent.getPreferredSize(); }

    @Override
    public Dimension minimumLayoutSize(Container parent) { return parent.getMinimumSize(); }

    @Override
    public void layoutContainer(Container parent) { /* rely on component bounds already set by AbsoluteConstraints usage */ }
}
